const express = require('express');
const router = express.Router();
const {
  getSuites,
  getSuiteById,
  createSuite,
  updateSuite,
  deleteSuite,
} = require('../services/testRunner');

/**
 * GET /api/suites - Retrieve list of all test suites from DB
 */
router.get('/', async (req, res) => {
  try {
    const suites = await getSuites();
    res.json(suites);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/suites/:id - Retrieve single test suite details including code
 */
router.get('/:id', async (req, res) => {
  try {
    const suite = await getSuiteById(req.params.id);
    if (!suite) {
      return res.status(404).json({ error: 'Suite not found' });
    }
    res.json(suite);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/suites - Create a new test suite
 */
router.post('/', async (req, res) => {
  try {
    const newSuite = await createSuite(req.body);
    res.status(201).json(newSuite);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * PUT /api/suites/:id - Update an existing test suite
 */
router.put('/:id', async (req, res) => {
  try {
    const updated = await updateSuite(req.params.id, req.body);
    res.json(updated);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * DELETE /api/suites/:id - Delete a test suite
 */
router.delete('/:id', async (req, res) => {
  try {
    const result = await deleteSuite(req.params.id);
    res.json(result);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * PATCH /api/suites/:id/schedule - Toggle or update schedule for a test suite
 */
router.patch('/:id/schedule', async (req, res) => {
  try {
    const { isScheduledEnabled, scheduleCron } = req.body;
    const updated = await updateSuite(req.params.id, {
      isScheduledEnabled,
      scheduleCron,
    });
    res.json(updated);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

const fs = require('fs');
const path = require('path');
const { spawn, exec } = require('child_process');
const config = require('../config');

// In-memory tracking for active codegen recording sessions
const activeCodegenSessions = new Map();

/**
 * POST /api/suites/codegen/start - Start auto-recording with Playwright CodeGen
 */
router.post('/codegen/start', async (req, res) => {
  try {
    const {
      name,
      targetUrl = 'http://localhost:5175/login',
      projectId = null,
      type = 'e2e',
      device = '',
      description = '',
      tags = ['auto-recorded', 'playwright-codegen'],
    } = req.body;

    const suiteName = name && name.trim() ? name.trim() : `Recorded Scenario ${new Date().toISOString().slice(0, 16).replace('T', ' ')}`;
    const sessionId = `rec-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
    
    // Prepare directory and temp file path
    const customDir = path.join(config.playwrightRoot, 'tests', 'custom');
    if (!fs.existsSync(customDir)) {
      fs.mkdirSync(customDir, { recursive: true });
    }

    const tempFilePath = path.join(customDir, `temp-${sessionId}.spec.ts`);

    const npxCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';
    const args = ['playwright', 'codegen', `--output=${tempFilePath}`];
    if (device && device.trim()) {
      args.push(`--device=${device.trim()}`);
    }
    args.push(targetUrl);

    console.log(`[CodeGen] Spawning: ${npxCmd} ${args.join(' ')}`);

    const child = spawn(npxCmd, args, {
      cwd: config.playwrightRoot,
      shell: true,
      stdio: 'ignore',
    });

    const sessionData = {
      sessionId,
      suiteName,
      targetUrl,
      projectId,
      type,
      device,
      description,
      tags: Array.isArray(tags) ? tags : [tags],
      tempFilePath,
      child,
      status: 'recording',
      startTime: Date.now(),
      suite: null,
      error: null,
    };

    activeCodegenSessions.set(sessionId, sessionData);

    child.on('close', async (exitCode) => {
      console.log(`[CodeGen] Session ${sessionId} child process exited with code ${exitCode}`);
      const sess = activeCodegenSessions.get(sessionId);
      if (!sess || sess.status === 'cancelled') return;

      try {
        if (!fs.existsSync(tempFilePath)) {
          sess.status = 'error';
          sess.error = 'No test file was generated by Playwright.';
          return;
        }

        let code = fs.readFileSync(tempFilePath, 'utf8').trim();
        // Remove temp file
        try { fs.unlinkSync(tempFilePath); } catch (e) {}

        if (!code || code.length < 20) {
          sess.status = 'empty';
          sess.error = 'Recording was closed without performing any actions.';
          return;
        }

        // Optimize generated code: ensure timeout and proper test description
        if (!code.includes('test.setTimeout')) {
          code = code.replace(
            /(test\s*\(\s*['"][^'"]*['"]\s*,\s*async\s*\(\s*\{\s*page\s*\}\s*\)\s*=>\s*\{)/,
            `$1\n    // 1. Extend timeout for remote environments / backend latency\n    test.setTimeout(60_000);\n`
          );
        }

        // Replace generic test name if present
        if (code.includes("test('test',")) {
          const safeTitle = sess.suiteName.replace(/'/g, "\\'");
          code = code.replace("test('test',", `test('${safeTitle}',`);
        }

        // Automatically create and register test suite in database
        const newSuite = await createSuite({
          name: sess.suiteName,
          projectId: sess.projectId,
          type: sess.type,
          description: sess.description || `Auto-recorded browser scenario on ${sess.targetUrl}`,
          project: sess.device ? 'mobile-chrome' : 'chromium',
          targetUrl: sess.targetUrl,
          code,
          tags: sess.tags,
        });

        sess.status = 'completed';
        sess.suite = newSuite;

        // Emit socket notification if io is available
        const io = req.app.get('io');
        if (io) {
          io.emit('codegen:completed', { sessionId, suite: newSuite });
          io.emit('suite:created', newSuite);
        }
        console.log(`[CodeGen] Successfully created suite "${newSuite.name}" (${newSuite.id})`);
      } catch (saveErr) {
        console.error(`[CodeGen] Failed to save recorded suite:`, saveErr);
        sess.status = 'error';
        sess.error = saveErr.message || 'Failed to save recorded test suite to database';
      }
    });

    child.on('error', (err) => {
      console.error(`[CodeGen] Process error on session ${sessionId}:`, err);
      const sess = activeCodegenSessions.get(sessionId);
      if (sess) {
        sess.status = 'error';
        sess.error = err.message || 'Failed to launch Playwright CodeGen';
      }
    });

    res.json({
      success: true,
      sessionId,
      suiteName,
      targetUrl,
      status: 'recording',
    });
  } catch (err) {
    console.error(`[CodeGen] Start error:`, err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/suites/codegen/status/:sessionId - Check recording status
 */
router.get('/codegen/status/:sessionId', (req, res) => {
  const session = activeCodegenSessions.get(req.params.sessionId);
  if (!session) {
    return res.status(404).json({ error: 'Session not found' });
  }
  res.json({
    sessionId: session.sessionId,
    status: session.status,
    suite: session.suite,
    error: session.error,
  });
});

/**
 * POST /api/suites/codegen/stop/:sessionId - Cancel or stop recording
 */
router.post('/codegen/stop/:sessionId', (req, res) => {
  const session = activeCodegenSessions.get(req.params.sessionId);
  if (!session) {
    return res.status(404).json({ error: 'Session not found' });
  }

  session.status = 'cancelled';
  if (session.child) {
    try {
      if (process.platform === 'win32') {
        exec(`taskkill /pid ${session.child.pid} /T /F`);
      } else {
        session.child.kill('SIGTERM');
      }
    } catch (e) {}
  }

  if (session.tempFilePath && fs.existsSync(session.tempFilePath)) {
    try { fs.unlinkSync(session.tempFilePath); } catch (e) {}
  }

  res.json({ success: true, message: 'Recording cancelled' });
});

/**
 * POST /api/suites/codegen - Launch Playwright CodeGen for manual interactive recording (backward compatibility)
 */
router.post('/codegen', (req, res) => {
  try {
    const targetUrl = req.body.url || 'http://localhost:5175/login';
    const deviceArg = req.body.device ? `--device="${req.body.device}" ` : '';
    // On Windows, use `cmd.exe /c start /min ""` to start minimized in the taskbar
    // so it doesn't block the screen, while Chromium and Playwright Inspector pop up in the foreground.
    const cmd = process.platform === 'win32'
      ? `cmd.exe /c start /min "" npx playwright codegen ${deviceArg}"${targetUrl}"`
      : `npx playwright codegen ${deviceArg}"${targetUrl}" &`;

    exec(cmd, { cwd: config.playwrightRoot }, (err) => {
      if (err) {
        console.error('[CodeGen] Execution error:', err);
      }
    });

    res.json({
      success: true,
      message: `Playwright CodeGen launched successfully for ${targetUrl}`,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;


